"use client";
import { useMemo, useState } from 'react';
import { formatMoney } from '@/lib/money';
type Product={id:string;name:string;slug:string;priceCents:number;status:string;stocks:{quantity:number}[]};
type Promotion={id:string;name:string;priceCents:number;description?:string;items:{quantity:number;product:Product}[]};
type CartItem={kind:'product'|'promotion';id:string;name:string;quantity:number;unitCents:number;flavors?:string[]};
export default function CardapioClient({products,promotions}:{products:Product[],promotions:Promotion[]}){const [cart,setCart]=useState<CartItem[]>([]);const [customer,setCustomer]=useState({customerName:'',customerPhone:'',deliveryType:'Retirada',address:''});const [error,setError]=useState('');const [ok,setOk]=useState('');
function addPromotion(p:Promotion){setCart(c=>{const i=c.findIndex(x=>x.kind==='promotion'&&x.id===p.id);if(i>=0){const n=[...c];n[i]={...n[i],quantity:n[i].quantity+1};return n}return [...c,{kind:'promotion',id:p.id,name:p.name,quantity:1,unitCents:p.priceCents,flavors:p.items.flatMap(it=>Array(it.quantity).fill(it.product.name.replace('Trufa de ','')))}]})}
function addProduct(p:Product){if(p.status!=='AVAILABLE'||(p.stocks[0]?.quantity??0)<=0)return;setCart(c=>{const i=c.findIndex(x=>x.kind==='product'&&x.id===p.id);if(i>=0){const n=[...c];n[i]={...n[i],quantity:n[i].quantity+1};return n}return [...c,{kind:'product',id:p.id,name:p.name,quantity:1,unitCents:p.priceCents}]})}
function inc(item:CartItem){setCart(c=>c.map(x=>x.kind===item.kind&&x.id===item.id?{...x,quantity:x.quantity+1}:x))}
function dec(item:CartItem){setCart(c=>c.map(x=>x.kind===item.kind&&x.id===item.id?{...x,quantity:x.quantity-1}:x).filter(x=>x.quantity>0))}
const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.quantity*i.unitCents,0),[cart]);
async function finish(){setError('');setOk(''); if(!cart.length){setError('Adicione produtos ao carrinho.');return} if(!customer.customerName||!customer.customerPhone){setError('Informe nome e WhatsApp.');return} const res=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...customer,items:cart})}); const data=await res.json(); if(!res.ok){setError(data.error||'Não foi possível finalizar.');return} setOk('Pedido finalizado e enviado para pedidos pendentes.'); setCart([]); if(data.whatsappUrl) window.open(data.whatsappUrl,'_blank')}
return <main className="max-w-6xl mx-auto p-5 grid md:grid-cols-[1fr_330px] gap-6"><section><h1 className="text-3xl font-black mb-4">Cardápio</h1><h2 className="font-black text-xl mb-2">Promoções</h2>{promotions.map(p=><div className="card p-5 mb-4" key={p.id}><b>{p.name}</b><p>{p.description}</p><p className="font-black">{formatMoney(p.priceCents)}</p><button className="btn mt-3" onClick={()=>addPromotion(p)}>Adicionar promoção</button></div>)}<h2 className="font-black text-xl mb-2">Trufas</h2><div className="grid sm:grid-cols-2 gap-4">{products.map(p=>{const q=p.stocks[0]?.quantity??0;const disabled=p.status!=='AVAILABLE'||q<=0;return <div className="card p-5" key={p.id}><b>{p.name}</b><p>{formatMoney(p.priceCents)}</p><p>Estoque: {q}</p>{disabled?<span className="font-black text-red-700">Indisponível</span>:<button className="btn mt-3" onClick={()=>addProduct(p)}>Adicionar</button>}</div>})}</div></section><aside className="card p-6 h-fit sticky top-4"><h2 className="font-black text-xl mb-6">Resumo</h2>{cart.map(item=><div key={item.kind+item.id} className="mb-3"><div className="grid grid-cols-[1fr_45px_30px_45px] items-center gap-2"><div><b>{item.name}</b>{item.flavors&&<p className="text-sm">{item.flavors.join(', ')}</p>}</div><button className="qty" onClick={()=>dec(item)}>-</button><b className="text-center">{item.quantity}</b><button className="qty" onClick={()=>inc(item)}>+</button></div></div>)}<div className="line my-3"></div><label>Nome<input className="w-full border p-2 rounded" value={customer.customerName} onChange={e=>setCustomer({...customer,customerName:e.target.value})}/></label><label>WhatsApp<input className="w-full border p-2 rounded" value={customer.customerPhone} onChange={e=>setCustomer({...customer,customerPhone:e.target.value})}/></label><select className="w-full border p-2 rounded mt-2" value={customer.deliveryType} onChange={e=>setCustomer({...customer,deliveryType:e.target.value})}><option>Retirada</option><option>Entrega</option></select>{customer.deliveryType==='Entrega'&&<input className="w-full border p-2 rounded mt-2" placeholder="Endereço" value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/>}<div className="line my-3"></div><p className="flex justify-between"><span>Produtos</span><b>{formatMoney(subtotal)}</b></p><p className="flex justify-between"><span>Frete</span><b>{formatMoney(0)}</b></p><p className="flex justify-between text-2xl mt-3"><span>Total</span><b>{formatMoney(subtotal)}</b></p>{error&&<p className="error mt-3">{error}</p>}{ok&&<p className="mt-3 bg-green-50 border border-green-200 rounded p-2">{ok}</p>}<button className="btn w-full mt-4" onClick={finish}>Finalizar pedido</button></aside></main>}
